package io.atworks.specscan.analysis.domain.fact;

public enum FactEdgeType { CALLS, CREATES, EXECUTES, REFERENCES, HAS_ARGUMENT, RECEIVER_OF, READS, ASSIGNED_FROM, COMPARES_WITH, OPERAND_OF,
    CONTROLS, THEN_OUTCOME, ELSE_OUTCOME, ORIGINATES_FROM, RETURNS, THROWS, HANDLED_BY, MAPS_TO, VALUE_FLOWS_TO }
