package io.atworks.specscan.analysis.domain.fact;

public enum FactNodeType { API_METHOD, METHOD, CONSTRUCTOR, OBJECT_CREATION, LAMBDA, METHOD_REFERENCE, PARAMETER, LOCAL_VARIABLE, FIELD_ACCESS, VALUE_FIELD, ENUM_CONSTANT, LITERAL, NULL_LITERAL, METHOD_CALL, CONDITION, THROW, RETURN, EXCEPTION, EXCEPTION_HANDLER, HTTP_STATUS }
