plugins {
    id 'java'
    id 'application'
}

group = 'io.atworks.specscan'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'io.atworks.specscan.SpecScanDemoRunner'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.eclipse.jgit:org.eclipse.jgit:6.8.0.202311291450-r'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.github.javaparser:javaparser-core:3.25.7'
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
