package io.atworks.specscan.analysis.recipe;

import io.atworks.specscan.analysis.domain.recipe.*;
import io.atworks.specscan.analysis.support.recipe.*;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class RecipeDemoReportTest {
    @Test void writesHumanReadableYamlExecutionReport() throws Exception {
        CompiledRecipePlan plan = new RecipePlanBootstrapService().bootstrap(new RecipeSourceSet(
            Path.of("src/test/resources/recipe-u04/engine-config.yaml"),
            Path.of("src/test/resources/recipe-u04/semantic-recipes.yaml"),
            Path.of("src/test/resources/recipe-u04/framework-catalog.yaml"))).plan();
        StringBuilder report = new StringBuilder("# YAML Recipe Demo Report\n\n");
        report.append("Generated by `RecipeDemoReportTest`. Evaluation-only; Java scan unchanged.\n\n");
        SemanticRecipeExecutor executor = new SemanticRecipeExecutor();
        for (SemanticRecipe recipe : plan.recipes()) {
            RecipeExecutionResult result = executor.execute(plan, recipe,
                new RecipeEvaluationContext("demo-repository", "GET /demo", "OrderController.check",
                    name -> Optional.of("request.amount"), new RuntimeBudget(plan.engine())));
            report.append("## ").append(recipe.id()).append("\n\n")
                .append("- Family: `").append(recipe.family()).append("`\n")
                .append("- Candidate: `OrderController.check`\n")
                .append("- Status: `").append(result.status()).append("`\n")
                .append("- Primitive steps: ").append(result.primitiveInvocations()).append("\n")
                .append("- Bindings: `").append(result.bindings().snapshot()).append("`\n\n");
        }
        Path output = Path.of("build/reports/yaml-recipe-demo.md");
        Files.createDirectories(output.getParent());
        Files.writeString(output, report.toString());
        assertThat(Files.readString(output)).contains("JAVA_BINARY_FAILURE_GUARD", "RESOLVED");
    }
}
