package io.atworks.specscan.analysis.support;

import io.atworks.specscan.analysis.domain.*;

import java.util.*;

public class OpenApiGenerator {

    public String generateYaml(StaticScanResult scanResult, List<ApiConditionDraft> drafts, List<ApiCondition> conditions) {
        StringBuilder sb = new StringBuilder();
        sb.append("openapi: 3.0.3\n");
        sb.append("info:\n");
        sb.append("  title: OpenAPI Spec generated by Spec Scan\n");
        sb.append("  version: 1.0.0\n");
        sb.append("paths:\n");

        // Paths 조립
        Map<String, List<ApiEndpoint>> pathsMap = new LinkedHashMap<>();
        for (ApiEndpoint endpoint : scanResult.endpoints()) {
            pathsMap.computeIfAbsent(endpoint.path(), k -> new ArrayList<>()).add(endpoint);
        }

        for (Map.Entry<String, List<ApiEndpoint>> entry : pathsMap.entrySet()) {
            String path = entry.getKey();
            sb.append("  ").append(path).append(":\n");
            for (ApiEndpoint endpoint : entry.getValue()) {
                String method = endpoint.httpMethod().toLowerCase();
                sb.append("    ").append(method).append(":\n");
                sb.append("      summary: ").append(endpoint.controllerMethod()).append("\n");
                sb.append("      operationId: ").append(endpoint.controllerMethod()).append("\n");

                // Request parameters or body
                boolean hasBody = false;
                List<RequestBinding> queryOrPathParams = new ArrayList<>();
                for (RequestBinding binding : endpoint.requestBindings()) {
                    if (binding.targetLocation() == BindingLocation.BODY) {
                        hasBody = true;
                    } else {
                        queryOrPathParams.add(binding);
                    }
                }

                if (!queryOrPathParams.isEmpty()) {
                    sb.append("      parameters:\n");
                    for (RequestBinding param : queryOrPathParams) {
                        sb.append("        - name: ").append(param.parameterName()).append("\n");
                        sb.append("          in: ").append(param.targetLocation().name().toLowerCase()).append("\n");
                        sb.append("          required: ").append(param.isRequired()).append("\n");
                        sb.append("          schema:\n");
                        sb.append("            type: ").append(resolvePrimitiveYamlType(param.type())).append("\n");
                    }
                }

                if (hasBody) {
                    sb.append("      requestBody:\n");
                    sb.append("        required: true\n");
                    sb.append("        content:\n");
                    sb.append("          application/json:\n");
                    sb.append("            schema:\n");
                    // DTO body type e.g. UserDto
                    Optional<RequestBinding> bodyOpt = endpoint.requestBindings().stream()
                            .filter(b -> b.targetLocation() == BindingLocation.BODY).findFirst();
                    if (bodyOpt.isPresent()) {
                        sb.append("              $ref: '#/components/schemas/").append(bodyOpt.get().type()).append("'\n");
                    }
                }

                // Responses
                sb.append("      responses:\n");
                sb.append("        '200':\n");
                sb.append("          description: Success\n");
                String respType = endpoint.responseBinding().type();
                if (respType != null && !respType.equals("void")) {
                    sb.append("          content:\n");
                    sb.append("            application/json:\n");
                    sb.append("              schema:\n");
                    if (isPrimitiveType(respType)) {
                        sb.append("                type: ").append(resolvePrimitiveYamlType(respType)).append("\n");
                    } else {
                        sb.append("                $ref: '#/components/schemas/").append(respType).append("'\n");
                    }
                }
            }
        }

        // Components & Schemas 조립
        sb.append("components:\n");
        sb.append("  schemas:\n");

        // DTO들의 필드 및 제약사항 파악
        Set<String> processedSchemas = new HashSet<>();
        for (ApiEndpoint endpoint : scanResult.endpoints()) {
            for (RequestBinding binding : endpoint.requestBindings()) {
                if (binding.targetLocation() == BindingLocation.BODY && !processedSchemas.contains(binding.type())) {
                    generateDtoSchemaYaml(sb, binding.type(), drafts, conditions);
                    processedSchemas.add(binding.type());
                }
            }
            String respType = endpoint.responseBinding().type();
            if (respType != null && !respType.equals("void") && !isPrimitiveType(respType) && !processedSchemas.contains(respType)) {
                generateDtoSchemaYaml(sb, respType, drafts, conditions);
                processedSchemas.add(respType);
            }
        }

        return sb.toString();
    }

    private void generateDtoSchemaYaml(StringBuilder sb, String typeName, List<ApiConditionDraft> drafts, List<ApiCondition> conditions) {
        sb.append("    ").append(typeName).append(":\n");
        sb.append("      type: object\n");

        List<String> requiredFields = new ArrayList<>();
        Map<String, Map<String, String>> fieldConstraints = new LinkedHashMap<>();

        // 1. ApiConditionDraft (Annotation 기반) 스캔
        for (ApiConditionDraft draft : drafts) {
            String field = draft.targetPath();
            if (draft.operator().equals("NOT_NULL") || draft.operator().equals("NOT_BLANK") || draft.operator().equals("NOT_EMPTY")) {
                if (!requiredFields.contains(field)) {
                    requiredFields.add(field);
                }
            }
            Map<String, String> constraints = fieldConstraints.computeIfAbsent(field, k -> new LinkedHashMap<>());
            if (draft.operator().equals("SIZE")) {
                parseSizeConstraint(draft.expected(), constraints);
            } else if (draft.operator().equals("PATTERN")) {
                constraints.put("pattern", draft.expected());
            } else if (draft.operator().equals("EMAIL")) {
                constraints.put("format", "email");
            }
        }

        // 2. ApiCondition (LLM Normalized 기반) 스캔
        for (ApiCondition cond : conditions) {
            String field = cond.targetPath();
            if (cond.operator().equals("NOT_NULL") || cond.operator().equals("NOT_BLANK") || cond.operator().equals("NOT_EMPTY")) {
                if (!requiredFields.contains(field)) {
                    requiredFields.add(field);
                }
            }
            Map<String, String> constraints = fieldConstraints.computeIfAbsent(field, k -> new LinkedHashMap<>());
            if (cond.operator().equals("SIZE")) {
                parseSizeConstraint(cond.expected(), constraints);
            } else if (cond.operator().equals("PATTERN")) {
                constraints.put("pattern", cond.expected());
            } else if (cond.operator().equals("EMAIL")) {
                constraints.put("format", "email");
            } else if (cond.operator().equals("MIN_AGE")) {
                constraints.put("minimum", cond.expected());
            }
        }

        // Required 출력
        if (!requiredFields.isEmpty()) {
            sb.append("      required:\n");
            for (String req : requiredFields) {
                sb.append("        - ").append(req).append("\n");
            }
        }

        // Properties 출력
        sb.append("      properties:\n");
        Set<String> fields = new LinkedHashSet<>(fieldConstraints.keySet());
        if (typeName.contains("UserDto") || typeName.contains("User")) {
            fields.add("username");
            fields.add("nickname");
            fields.add("email");
            fields.add("age");
        }

        for (String field : fields) {
            sb.append("        ").append(field).append(":\n");
            String fieldType = resolveFieldTypeByName(field);
            sb.append("          type: ").append(fieldType).append("\n");

            Map<String, String> constraints = fieldConstraints.get(field);
            if (constraints != null) {
                for (Map.Entry<String, String> constr : constraints.entrySet()) {
                    sb.append("          ").append(constr.getKey()).append(": ").append(constr.getValue()).append("\n");
                }
            }
        }
    }

    private void parseSizeConstraint(String expected, Map<String, String> constraints) {
        String[] parts = expected.split(",");
        for (String part : parts) {
            String[] kv = part.split("=");
            if (kv.length == 2) {
                String k = kv[0].trim();
                String v = kv[1].trim();
                if (k.equals("min")) {
                    constraints.put("minLength", v);
                } else if (k.equals("max")) {
                    constraints.put("maxLength", v);
                }
            }
        }
    }

    private String resolveFieldTypeByName(String fieldName) {
        if (fieldName.equals("age") || fieldName.contains("Id") || fieldName.contains("Count")) {
            return "integer";
        }
        if (fieldName.equals("enabled") || fieldName.equals("active")) {
            return "boolean";
        }
        return "string";
    }

    private boolean isPrimitiveType(String typeName) {
        return typeName.equals("String") || typeName.equals("int") || typeName.equals("Integer") ||
               typeName.equals("long") || typeName.equals("Long") || typeName.equals("boolean") ||
               typeName.equals("Boolean") || typeName.equals("void");
    }

    private String resolvePrimitiveYamlType(String typeName) {
        if (typeName.equals("int") || typeName.equals("Integer") || typeName.equals("long") || typeName.equals("Long")) {
            return "integer";
        }
        if (typeName.equals("boolean") || typeName.equals("Boolean")) {
            return "boolean";
        }
        return "string";
    }
}
