package io.atworks.specscan.analysis.support;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public class OpenApiGenerator {

    private static final Set<String> RESERVED_SCALARS = Set.of(
        "null", "true", "false", "yes", "no", "on", "off", "~"
    );

    private final ObjectMapper objectMapper;

    public OpenApiGenerator() {
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    public String generateYaml(String executionJson) {
        try {
            return generateYaml(objectMapper.readTree(executionJson));
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to parse execution model JSON.", e);
        }
    }

    String generateYaml(JsonNode executionModel) {
        StringBuilder sb = new StringBuilder();
        sb.append("openapi: 3.0.3\n");
        sb.append("info:\n");
        sb.append("  title: OpenAPI Spec generated by Spec Scan\n");
        sb.append("  version: 1.0.0\n");
        sb.append("paths:\n");

        for (Map.Entry<String, List<JsonNode>> entry : groupOperationsByPath(executionModel.path("operations")).entrySet()) {
            appendLine(sb, 1, entry.getKey() + ":");
            for (JsonNode operation : entry.getValue()) {
                appendOperation(sb, operation);
            }
        }

        return sb.toString();
    }

    private Map<String, List<JsonNode>> groupOperationsByPath(JsonNode operationsNode) {
        Map<String, List<JsonNode>> operationsByPath = new LinkedHashMap<>();
        if (!operationsNode.isArray()) {
            return operationsByPath;
        }
        for (JsonNode operation : operationsNode) {
            String path = operation.path("path").asText();
            operationsByPath.computeIfAbsent(path, _k -> new ArrayList<>()).add(operation);
        }
        return operationsByPath;
    }

    private void appendOperation(StringBuilder sb, JsonNode operation) {
        String method = operation.path("method").asText().toLowerCase(Locale.ROOT);
        appendLine(sb, 2, method + ":");

        String operationId = operation.path("operationId").asText();
        appendLine(sb, 3, "summary: " + formatString(operationId));
        appendLine(sb, 3, "operationId: " + formatString(operationId));

        JsonNode request = operation.path("request");
        appendParameters(sb, request);
        appendRequestBody(sb, request);
        appendResponses(sb, operation.path("response200"));
        appendValidationConditions(sb, operation.path("validationConditions"));
    }

    private void appendParameters(StringBuilder sb, JsonNode request) {
        List<ParameterGroup> groups = List.of(
            new ParameterGroup("pathParams", "path"),
            new ParameterGroup("queryParams", "query"),
            new ParameterGroup("headers", "header")
        );
        boolean hasParameters = groups.stream().anyMatch(group -> request.path(group.nodeName()).isArray() && request.path(group.nodeName()).size() > 0);
        if (!hasParameters) {
            return;
        }

        appendLine(sb, 3, "parameters:");
        for (ParameterGroup group : groups) {
            JsonNode params = request.path(group.nodeName());
            if (!params.isArray()) {
                continue;
            }
            for (JsonNode parameter : params) {
                appendLine(sb, 4, "- name: " + formatString(parameter.path("name").asText()));
                appendLine(sb, 5, "in: " + group.openapiLocation());
                appendLine(sb, 5, "required: " + parameter.path("required").asBoolean(false));
                if (!parameter.path("description").isMissingNode() && !parameter.path("description").isNull()) {
                    appendLine(sb, 5, "description: " + formatScalar(parameter.path("description")));
                }
                if (!parameter.path("example").isMissingNode() && !parameter.path("example").isNull()) {
                    appendLine(sb, 5, "example: " + formatScalar(parameter.path("example")));
                }
                appendLine(sb, 5, "schema:");
                appendSchema(sb, 6, parameter.path("schema"));
                if (!parameter.path("defaultValue").isMissingNode() && !parameter.path("defaultValue").isNull()) {
                    appendLine(sb, 6, "default: " + formatScalar(parameter.path("defaultValue")));
                }
                if (parameter.path("enumValues").isArray() && parameter.path("enumValues").size() > 0) {
                    appendLine(sb, 6, "enum:");
                    for (JsonNode enumValue : parameter.path("enumValues")) {
                        appendLine(sb, 7, "- " + formatScalar(enumValue));
                    }
                }
            }
        }
    }

    private void appendRequestBody(StringBuilder sb, JsonNode request) {
        JsonNode contentType = request.path("contentType");
        JsonNode bodySchema = request.path("bodySchema");
        if (contentType.isMissingNode() || contentType.isNull() || bodySchema.isMissingNode() || bodySchema.isNull()) {
            return;
        }

        appendLine(sb, 3, "requestBody:");
        appendLine(sb, 4, "required: true");
        appendLine(sb, 4, "content:");
        appendLine(sb, 5, contentType.asText() + ":");
        appendLine(sb, 6, "schema:");
        appendSchema(sb, 7, bodySchema);
        if (!request.path("bodyExample").isMissingNode() && !request.path("bodyExample").isNull()) {
            appendLine(sb, 6, "example:");
            appendGenericNode(sb, 7, request.path("bodyExample"));
        }
    }

    private void appendResponses(StringBuilder sb, JsonNode response) {
        appendLine(sb, 3, "responses:");
        appendLine(sb, 4, "'200':");
        appendLine(sb, 5, "description: Success");

        JsonNode contentType = response.path("contentType");
        JsonNode schema = response.path("schema");
        if (contentType.isMissingNode() || contentType.isNull() || schema.isMissingNode() || schema.isNull()) {
            return;
        }

        appendLine(sb, 5, "content:");
        appendLine(sb, 6, contentType.asText() + ":");
        appendLine(sb, 7, "schema:");
        appendSchema(sb, 8, schema);
        if (!response.path("example").isMissingNode() && !response.path("example").isNull()) {
            appendLine(sb, 7, "example:");
            appendGenericNode(sb, 8, response.path("example"));
        }
    }

    private void appendValidationConditions(StringBuilder sb, JsonNode validationConditions) {
        if (!validationConditions.isArray() || validationConditions.isEmpty()) {
            return;
        }

        appendLine(sb, 3, "x-validation-conditions:");
        for (JsonNode condition : validationConditions) {
            appendLine(sb, 4, "- targetLocation: " + formatScalar(condition.path("targetLocation")));
            appendLine(sb, 5, "targetPath: " + formatScalar(condition.path("targetPath")));
            appendLine(sb, 5, "operator: " + formatScalar(condition.path("operator")));
            if (!condition.path("expected").isMissingNode() && !condition.path("expected").isNull()) {
                appendLine(sb, 5, "expected: " + formatScalar(condition.path("expected")));
            }
            appendLine(sb, 5, "source: " + formatScalar(condition.path("source")));
        }
    }

    private void appendSchema(StringBuilder sb, int indent, JsonNode schema) {
        if (schema == null || schema.isMissingNode() || schema.isNull()) {
            appendLine(sb, indent, "type: object");
            return;
        }

        appendIfPresent(sb, indent, "type", schema.get("type"));
        appendIfPresent(sb, indent, "format", schema.get("format"));
        appendIfPresent(sb, indent, "minimum", schema.get("minimum"));
        appendIfPresent(sb, indent, "maximum", schema.get("maximum"));
        appendIfPresent(sb, indent, "minLength", schema.get("minLength"));
        appendIfPresent(sb, indent, "maxLength", schema.get("maxLength"));
        appendIfPresent(sb, indent, "pattern", schema.get("pattern"));

        JsonNode enumValues = schema.get("enumValues");
        if (enumValues != null && enumValues.isArray() && enumValues.size() > 0) {
            appendLine(sb, indent, "enum:");
            for (JsonNode enumValue : enumValues) {
                appendLine(sb, indent + 1, "- " + formatScalar(enumValue));
            }
        }

        JsonNode required = schema.get("required");
        if (required != null && required.isArray() && required.size() > 0) {
            appendLine(sb, indent, "required:");
            for (JsonNode requiredField : required) {
                appendLine(sb, indent + 1, "- " + formatScalar(requiredField));
            }
        }

        JsonNode properties = schema.get("properties");
        if (properties != null && properties.isObject() && properties.size() > 0) {
            appendLine(sb, indent, "properties:");
            properties.fields().forEachRemaining(entry -> {
                appendLine(sb, indent + 1, entry.getKey() + ":");
                appendSchema(sb, indent + 2, entry.getValue());
            });
        }

        JsonNode items = schema.get("items");
        if (items != null && !items.isNull() && !items.isMissingNode()) {
            appendLine(sb, indent, "items:");
            appendSchema(sb, indent + 1, items);
        }

        JsonNode additionalProperties = schema.get("additionalProperties");
        if (additionalProperties != null && !additionalProperties.isNull() && !additionalProperties.isMissingNode()) {
            if (additionalProperties.isBoolean()) {
                appendLine(sb, indent, "additionalProperties: " + additionalProperties.asBoolean());
            } else {
                appendLine(sb, indent, "additionalProperties:");
                appendSchema(sb, indent + 1, additionalProperties);
            }
        }
    }

    private void appendGenericNode(StringBuilder sb, int indent, JsonNode node) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            appendLine(sb, indent, "null");
            return;
        }
        if (node.isObject()) {
            node.fields().forEachRemaining(entry -> appendNamedGenericNode(sb, indent, entry.getKey(), entry.getValue()));
            return;
        }
        if (node.isArray()) {
            if (node.isEmpty()) {
                appendLine(sb, indent, "[]");
                return;
            }
            for (JsonNode item : node) {
                if (isScalar(item)) {
                    appendLine(sb, indent, "- " + formatScalar(item));
                } else {
                    appendLine(sb, indent, "-");
                    appendGenericNode(sb, indent + 1, item);
                }
            }
            return;
        }
        appendLine(sb, indent, formatScalar(node));
    }

    private void appendNamedGenericNode(StringBuilder sb, int indent, String key, JsonNode value) {
        if (isScalar(value)) {
            appendLine(sb, indent, key + ": " + formatScalar(value));
            return;
        }
        appendLine(sb, indent, key + ":");
        appendGenericNode(sb, indent + 1, value);
    }

    private void appendIfPresent(StringBuilder sb, int indent, String key, JsonNode value) {
        if (value == null || value.isMissingNode() || value.isNull()) {
            return;
        }
        appendLine(sb, indent, key + ": " + formatScalar(value));
    }

    private boolean isScalar(JsonNode node) {
        return node.isValueNode();
    }

    private String formatScalar(JsonNode value) {
        if (value == null || value.isNull()) {
            return "null";
        }
        if (value.isBoolean() || value.isNumber()) {
            return value.toString();
        }
        return formatString(value.asText());
    }

    private String formatString(String value) {
        if (value == null) {
            return "null";
        }
        if (value.isEmpty()) {
            return "''";
        }
        if (isPlainSafe(value)) {
            return value;
        }
        return "'" + value.replace("'", "''") + "'";
    }

    private boolean isPlainSafe(String value) {
        if (value.isBlank() || !value.equals(value.trim())) {
            return false;
        }
        if (value.contains("\n") || value.contains("\r") || value.contains(": ")) {
            return false;
        }
        char first = value.charAt(0);
        if (first == '-' || first == '?' || first == '@' || first == '*' || first == '&' || first == '!' || first == '%') {
            return false;
        }
        for (char current : value.toCharArray()) {
            if (current == '#' || current == '{' || current == '}' || current == '[' || current == ']' || current == ',') {
                return false;
            }
        }
        return !RESERVED_SCALARS.contains(value.toLowerCase(Locale.ROOT));
    }

    private void appendLine(StringBuilder sb, int indent, String text) {
        sb.append("  ".repeat(indent)).append(text).append('\n');
    }

    private record ParameterGroup(String nodeName, String openapiLocation) {}
}
